package guru.sfg.beer.order.service.domain;

public enum OrdenEstadoCervezaEnum {
    NUEVO, VALIDADO, VALIDACION_EXCEPCION, ASIGNADO, ASIGNACION_EXCEPCION,
    INVENTARIO_PENDIENTE, RETIRADO, ENTREGADO, ENTREGA_EXCEPCION
}
