package guru.sfg.beer.order.service.domain;

public enum OrdenEstadoCervezaEnum {
    NUEVO, VALIDADO, VALIDACION_PENDIENTE, VALIDACION_EXCEPCION, ASIGNADO_PENDIENTE, ASIGNADO, ASIGNACION_EXCEPCION, CANCELADO,
    INVENTARIO_PENDIENTE, RETIRADO, ENTREGADO, ENTREGA_EXCEPCION
}
