package guru.sfg.beer.order.service.domain;

public enum OrdenEventoCervezaEnum {
   VALIDAR_PEDIDO, CANCELAR_ORDEN, VALIDACION_APROBADA, VALIDACION_FALLIDA,
   ASIGNAR_PEDIDO, ASIGNACION_EXITOSA, ASIGNACION_SIN_INVENTARIO, ASIGNACION_FALLIDA,
   PEDIDO_CERVEZA_ENTREGADO
}